import {MilestoneName} from '@/common/ma/MilestoneName';
import {AwardName} from '@/common/ma/AwardName';

// Symbol je Meilenstein/Auszeichnung aus den vorhandenen Bildern unter assets/ (Zuordnung abgestimmt in
// "Claude outputs/meilensteine-icons.html"). Mehrere Teile = Summe (z. B. Stahl + Titan);
// production = im braunen Produktionskasten wie auf den Karten.
// Record über alle Namen: fehlt ein neuer Meilenstein/eine neue Auszeichnung, meldet das der Typprüfer.
export type IconPart = {
  asset: string;
  production?: boolean;
  // Optische Mitte in Prozent der Breite, falls das Bild nicht symmetrisch ist (Grünfläche mit Marker oben rechts)
  centerX?: number;
  // Weiße Kontur für dunkle Bilder, die sonst im dunklen Hintergrund verschwinden (schwarze Karte)
  outline?: boolean;
};

export const MILESTONE_ICONS: Record<MilestoneName, ReadonlyArray<IconPart>> = {
  'Agronomist': [{asset: 'tags/plant'}],
  'Architect': [{asset: 'tags/city'}],
  'Briber': [{asset: 'resources/megacredit'}],
  'Builder': [{asset: 'tags/building'}],
  'Builder7': [{asset: 'tags/building'}],
  'C. Forester': [{asset: 'resources/plant', production: true}],
  'Capitalist': [{asset: 'resources/megacredit'}],
  'Coastguard': [{asset: 'tiles/ocean'}],
  'Colonizer': [{asset: 'tiles/colony'}],
  'Diversifier': [{asset: 'tags/wild'}],
  'Ecologist': [{asset: 'tags/plant'}, {asset: 'tags/microbe'}, {asset: 'tags/animal'}],
  'Economizer': [{asset: 'resources/heat', production: true}],
  'Energizer': [{asset: 'resources/power', production: true}],
  'Engineer': [{asset: 'resources/power', production: true}, {asset: 'resources/heat', production: true}],
  'Farmer': [{asset: 'resources/animal'}, {asset: 'resources/microbe'}],
  'Firestarter': [{asset: 'resources/heat'}],
  'Forester': [{asset: 'resources/plant', production: true}],
  'Fundraiser': [{asset: 'resources/megacredit', production: true}],
  'Gambler': [{asset: 'resources/megacredit'}],
  'Gardener': [{asset: 'tiles/greenery', centerX: 43}],
  'Generalist': [{asset: 'resources/wild', production: true}],
  'Geologist': [{asset: 'hex_volcanic'}],
  'Hoverlord': [{asset: 'resources/floater'}],
  'Hydrologist': [{asset: 'tiles/ocean'}],
  'Irrigator': [{asset: 'tiles/ocean'}],
  'Land Specialist': [{asset: 'tiles/special'}],
  'Landshaper': [{asset: 'tiles/city'}, {asset: 'tiles/greenery', centerX: 43}, {asset: 'tiles/special'}],
  'Legend': [{asset: 'tags/event'}],
  'Legend4': [{asset: 'tags/event'}],
  'Lobbyist': [{asset: 'misc/delegate'}],
  'Lunarchitect': [{asset: 'tags/moon'}],
  'Martian': [{asset: 'tags/mars'}],
  'Mayor': [{asset: 'tiles/city'}],
  'Merchant': [{asset: 'resources/wild-std'}],
  'Metallurgist': [{asset: 'resources/steel', production: true}, {asset: 'resources/titanium', production: true}],
  'Minimalist': [{asset: 'resources/card', outline: true}],
  'Networker': [{asset: 'tiles/adjacency_bonus'}],
  'One Giant Step': [{asset: 'tags/moon'}],
  'Philantropist': [{asset: 'resources/card', outline: true}],
  'Pioneer': [{asset: 'tiles/colony'}],
  'Pioneer4': [{asset: 'tiles/colony'}],
  'Planetologist': [{asset: 'tags/earth'}, {asset: 'tags/venus'}, {asset: 'tags/jovian'}],
  'Planner': [{asset: 'resources/card', outline: true}],
  'Polar Explorer': [{asset: 'tiles/empty'}],
  'Producer': [{asset: 'resources/wild', production: true}],
  'Purifier': [{asset: 'tiles/hazard'}],
  'Researcher': [{asset: 'resources/science'}],
  'Rim Settler': [{asset: 'tags/jovian'}],
  'Risktaker': [{asset: 'underworld/negative-vp'}],
  'Smith': [{asset: 'resources/steel', production: true}, {asset: 'resources/titanium', production: true}],
  'Spacefarer': [{asset: 'tags/space'}],
  'Spacefarer4': [{asset: 'tags/space'}],
  'Specialist': [{asset: 'resources/wild', production: true}],
  'Sponsor': [{asset: 'resources/card', outline: true}],
  'T. Collector': [{asset: 'resources/card', outline: true}],
  'Tactician': [{asset: 'resources/card', outline: true}],
  'Tactician4': [{asset: 'resources/card', outline: true}],
  'Terra Pioneer': [{asset: 'tiles/empty'}],
  'Terraformer': [{asset: 'resources/tr'}],
  'Terraformer29': [{asset: 'resources/tr'}],
  'Terran': [{asset: 'tags/earth'}],
  'Terran5': [{asset: 'tags/earth'}],
  'Thawer': [{asset: 'global-parameters/temperature'}],
  'Trader': [{asset: 'resources/wild'}],
  'Tradesman': [{asset: 'resources/wild'}],
  'Tropicalist': [{asset: 'tiles/empty'}],
  'Tunneler': [{asset: 'underworld/underground-token-background'}],
  'Tycoon': [{asset: 'resources/card', outline: true}],
  'Tycoon10': [{asset: 'resources/card', outline: true}],
  'V. Electrician': [{asset: 'tags/power'}],
  'V. Spacefarer': [{asset: 'tags/space'}],
};

export const AWARD_ICONS: Record<AwardName, ReadonlyArray<IconPart>> = {
  'A. Engineer': [{asset: 'resources/wild', production: true}],
  'A. Manufacturer': [{asset: 'resources/card', outline: true}],
  'A. Zoologist': [{asset: 'resources/animal'}, {asset: 'resources/microbe'}],
  'Administrator': [{asset: 'tags/tag-none'}],
  'Banker': [{asset: 'resources/megacredit', production: true}],
  'Benefactor': [{asset: 'resources/tr'}],
  'Biologist': [{asset: 'tags/animal'}, {asset: 'tags/plant'}, {asset: 'tags/microbe'}],
  'Blacksmith': [{asset: 'resources/steel', production: true}, {asset: 'resources/titanium', production: true}],
  'Botanist': [{asset: 'resources/plant', production: true}],
  'Celebrity': [{asset: 'resources/card', outline: true}],
  'Collector': [{asset: 'resources/wild'}],
  'Constructor': [{asset: 'tiles/colony'}, {asset: 'tiles/city'}],
  'Contractor': [{asset: 'tags/building'}],
  'Cosmic Settler': [{asset: 'tiles/city'}],
  'Cultivator': [{asset: 'tiles/greenery', centerX: 43}],
  'Curator': [{asset: 'tags/wild'}],
  'Desert Settler': [{asset: 'tiles/empty'}],
  'Edgedancer': [{asset: 'tiles/empty'}],
  'Electrician': [{asset: 'tags/power'}],
  'Entrepreneur': [{asset: 'tiles/adjacency_bonus'}],
  'Estate Dealer': [{asset: 'tiles/ocean'}],
  'Excavator': [{asset: 'underworld/excavate'}],
  'Excentric': [{asset: 'resources/wild'}],
  'Forecaster': [{asset: 'resources/card', outline: true}],
  'Founder': [{asset: 'tiles/special'}],
  'Full Moon': [{asset: 'tags/moon'}],
  'Highlander': [{asset: 'tiles/empty'}],
  'Incorporator': [{asset: 'resources/card', outline: true}],
  'Industrialist': [{asset: 'resources/steel'}, {asset: 'resources/power'}],
  'Investor': [{asset: 'tags/earth'}],
  'Kingpin': [{asset: 'tags/crime'}],
  'Landlord': [{asset: 'tiles/empty'}],
  'Landscaper': [{asset: 'tiles/greenery', centerX: 43}],
  'Lunar Magnate': [{asset: 'tags/moon'}],
  'Magnate': [{asset: 'resources/card', outline: true}],
  'Manufacturer': [{asset: 'resources/steel', production: true}, {asset: 'resources/heat', production: true}],
  'Metropolist': [{asset: 'tiles/city'}],
  'Miner': [{asset: 'resources/steel'}, {asset: 'resources/titanium'}],
  'Mogul': [{asset: 'resources/wild', production: true}],
  'Naturalist': [{asset: 'resources/plant', production: true}, {asset: 'resources/heat', production: true}],
  'Politician': [{asset: 'misc/delegate'}, {asset: 'misc/influence'}],
  'Promoter': [{asset: 'tags/event'}],
  'Rugged': [{asset: 'tiles/hazard'}],
  'Scientist': [{asset: 'resources/science'}],
  'Space Baron': [{asset: 'tags/space'}],
  'Suburbian': [{asset: 'tiles/empty'}],
  'T. Politician': [{asset: 'misc/delegate'}],
  'Thermalist': [{asset: 'resources/heat'}],
  'Tourist': [{asset: 'tiles/empty'}],
  'Traveller': [{asset: 'tags/jovian'}, {asset: 'tags/earth'}],
  'Urbanist': [{asset: 'tiles/city'}],
  'Venuphile': [{asset: 'tags/venus'}],
  'Visionary': [{asset: 'resources/card', outline: true}],
  'Voyager': [{asset: 'tags/jovian'}],
  'Warmonger': [{asset: 'misc/minus'}],
  'Zoologist': [{asset: 'resources/animal'}],
};
